### ISSUE TITLE
Problem running this on Mac

### ISSUE THREAD

**Issue by vzelenko** [NetCoreTemplates/svelte-spa#1]
Mac OS has a program `x` (XQuartz) that is found in `/opt/X11/bin/x` on my machine, and is conflicting with the recommended tool.

Please add a note for Mac users with a workaround.  In my case, I've simply referred to the tool by it's physical path:  `~/.dotnet/tools/x` to bootstrap the project.

**Comment by mythz** [comment]
I'm assuming it's not installed by default as I've not had this issue through any of the different mac OS's I've run (folder doesn't exist in the macOS Catalina or Ben Sur Macs I'm running now) & no one else has reported this issue.

To resolve PATH conflicts you could move it to the start of shell profile script:

    export PATH=~/.dotnet/tools:$PATH

Or override just `x` to use the dotnet tool:

    alias x=~/.dotnet/tools/x

Or you could give it another alias:

    alias y=~/.dotnet/tools/x
