### ISSUE TITLE
getting 404 error when I publish and run in IIS as a application

### ISSUE THREAD

**Issue by RussKahler1970** [NetCoreTemplates/svelte-spa#2]
All the artifacts are trying to be accessed by http://localhost/assets/css/bootstrap.css  when it should be http://localhost/app2/assets/css/bootstrap.css. how do I get the app to work within an application in IIS?

Thanks

**Comment by mythz** [comment]
You should be able to either remove the `/` prefix to all references, e.g:

```html
	<link rel='stylesheet' href='assets/css/bootstrap.css'>
	<link rel='stylesheet' href='assets/css/global.css'>
	<link rel='stylesheet' href='bundle.css'>
</head>

<body>
    <i hidden>{{ 'js/hot-fileloader.js' |> ifDebugIncludeScript }}</i>

	<script src='bundle.js'></script>
	<script src='assets/js/jquery.slim.min.js'></script>
	<script src='assets/js/bootstrap.min.js'></script>
```

Or add a `{{BaseUrl}}` prefix to all resources, e.g:

```html
	<link rel='stylesheet' href='{{BaseUrl}}/assets/css/bootstrap.css'>
```

Although you'll generally want to host on a local port, e.g `https://localhost:5001` or use a virtual host for SPA Apps so you can have absolute references as full page reloads of deep nested routes wont work with relative references.
