### ISSUE TITLE
Error when run npm run dev

### ISSUE THREAD

**Issue by ryzam** [NetCoreTemplates/svelte-spa#4]
HI guys, I unable to run the code, when try execute npm run dev i got this error message.
![image](https://user-images.githubusercontent.com/597759/148633012-0d515637-7c40-4f6f-aea7-253acecbffc7.png)

**Comment by mythz** [comment]
This works without issue for me:

1. Download **Svelte SPA** from https://servicestack.net/start
https://account.servicestack.net/archive/NetCoreTemplates/svelte-spa

2. Open in Visual Studio
3. Install and run dev:

    $ npm run install
    $ npm run dev

<img width="376" alt="image" src="https://user-images.githubusercontent.com/89361/148641398-debfa7d2-4eb2-4965-926c-3a61658ffde1.png">
